### ISSUE TITLE
Error during running code

### ISSUE THREAD

**Issue by joelrodrigues-NCI** [stainleebakhla/mininet-flow-generator#1]
I am trying to use this flow generator in my implementation and I am getting following error.Someone please help for solving.

Traceback (most recent call last):
  File "topo_launcher.py", line 344, in <module>
    generate_flows(n_elephant_flows, n_mice_flows, experiment_duration, net, log_dir)
  File "topo_launcher.py", line 193, in generate_flows
    n = random.randint(1, interval)
  File "/usr/lib/python2.7/random.py", line 244, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 220, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (1,1, 0)

Thanks

**Comment by canerturkaslan** [comment]
please try with suggested numbers or you must find the sample numbers according to the algorithm to create
# n_mice_flows = 45
# n_elephant_flows = 5
# experiment_duration = 180 seconds
